### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by bjsi** [coldenate/rollover-daily-todos#1]
https://github.com/coldenate/rollover-daily-todos/blob/34b7cdca9d8fc6b46b0fc57fb770091005233d72/src/widgets/index.tsx#L126C40-L126C40

- I think this shortcut clashes with a built in shortcut (turn the focused rem into a document)
- Change `alt` to `opt` to support both mac + windows

https://github.com/coldenate/rollover-daily-todos/blob/34b7cdca9d8fc6b46b0fc57fb770091005233d72/src/widgets/index.tsx#L52C2-L52C69

- Unfortunately these settings make things a little more complicated :/ maybe I should just add another API method to reduce the complexity here.
- I think I'm getting an error here despite not changing these settings too
![image](https://github.com/coldenate/rollover-daily-todos/assets/58147075/1ae49561-769b-4f50-a7a2-00709b0b675a)

https://github.com/coldenate/rollover-daily-todos/blob/34b7cdca9d8fc6b46b0fc57fb770091005233d72/src/widgets/index.tsx#L219C1-L226C4

- If you are using dailyDoc.createdAt as a proxy for the date it represents it's not necessarily correct because you can create daily docs for future dates by typing !! and selecting a future date. Not sure if this is what you're doing though.

Great work, it's almost there :) I'll have some time to clone and run this locally to help debug tomorrow!

**Comment by coldenate** [comment]
I'll be removing the keyboard shortcut for the debug command just because it is a tad bit unnecessary.

**Comment by coldenate** [comment]
@bjsi Could you describe how I can reproduce the date error?

**Comment by coldenate** [comment]
> If you are using dailyDoc.createdAt as a proxy for the date it represents it's not necessarily correct because you can create daily docs for future dates by typing !! and selecting a future date. Not sure if this is what you're doing though.

The goal for the use is to have a value that describes when the document/rem was physically created. I was thinking of something like file creation date. 
Is there a behavior change with `createdAt` when using `!!`?

**Comment by bjsi** [comment]
- The date error doesn't seem to be happening for me anymore :thinking:
- Ok that sounds good, shouldn't be any problems with `createdAt`

https://github.com/coldenate/rollover-daily-todos/blob/34b7cdca9d8fc6b46b0fc57fb770091005233d72/src/widgets/index.tsx#L52C2-L52C69

![image](https://github.com/coldenate/rollover-daily-todos/assets/58147075/78b027cf-6446-4584-8054-073be3498a24)

- I can create an error if I change this setting, could you try getting the timestamp from the daily doc by accessing the timestamp slot instead? `dailyDoc.getPowerupProperty(BuiltInPowerupCodes.DailyDocument, PowerupSlotCodeMap[BuiltInPowerupCodes.DailyDocument].Timestamp`)

**Comment by bjsi** [comment]
I don't think many people use that setting, so I just approved the plugin :)

**Comment by coldenate** [comment]
Implementing this:
```ts
await dailyDocument.getPowerupProperty(BuiltInPowerupCodes.DailyDocument, 'Timestamp')
```

> `dailyDoc.getPowerupProperty(BuiltInPowerupCodes.DailyDocument, PowerupSlotCodeMap[BuiltInPowerupCodes.DailyDocument].Timestamp)` 

This seemed to fail. `PowerupSlotCodeMap[BuiltInPowerupCodes.DailyDocument].Timestamp` evaluates to `'s'`, but the method was expecting `'Timestamp'` in place of the property code. I think this may just be because the sdk got a lot of updates between now and then. 😅 
Thanks for the improved method of getting the date! It used to be broken with ISO, but now it's fixed.
