### ISSUE TITLE
Doesn't work in my remnote

### ISSUE THREAD

**Issue by sjsorock** [coldenate/rollover-daily-todos#2]
I think your plugin shouldn't need to set other parameters, it won't work in my remnote after installation

**Comment by coldenate** [comment]
hey! @sjsorock thanks for reaching out. Would you mind elaborating on the parameters you think it shouldn't set, and could you give some context on your Rem knowledgebase that would be incompatible with the plugin?

And have you tried using the debug commands to force the rollover?
The command's name is `Rollover Unfinished Todos`.

**Comment by sjsorock** [comment]
Yes, I used the force command, the upper right corner shows how I provided incompatible related content that ran but nothing actually happened

**Comment by coldenate** [comment]
Would you be able to provide any extra details, videos, screenshots, or steps on how I can reproduce this error myself? @sjsorock
