### ISSUE TITLE
Automated rollover not working 

### ISSUE THREAD

**Issue by cagataytuylu** [coldenate/rollover-daily-todos#22]
Automated rollover not working

**Comment by coldenate** [comment]
Hi! Thank you for stopping by! Could you please complete the following steps to give me an idea of what your KB looks like?

1. Does running the command `/rollover` manually do anything? Can we narrow this down to the Automatic part?
2. Can you send a screenshot or type out what settings you use in Rollover Daily Todos? 
3. What day are your Todos from? (Which daily document? can be multiple ofc)
4. Are you using Omnirollover at all?

Then, to try and fix the issue automatically:
1. Enable Debug Mode in the Plugin Settings
2. Run the command Debug Auto Rollover 
3. Wait a bit

**Comment by cagataytuylu** [comment]
1. Yes command working and only installed extension is yours


3. Official daily only

4. Yes

13 Oca 2024 Cmt, saat 00:59 tarihinde Nate Solis ***@***.***>
şunu yazdı:

**Comment by coldenate** [comment]
Ah okay. Thank you. These steps should fix it:

1. Enable Debug Mode in the Plugin Settings
2. Run the command Debug Auto Rollover

Please let me know if this does not work!
