### ISSUE TITLE
Is it possible to provide a configuration item that does not rollover for todo's of a given tag?

### ISSUE THREAD

**Issue by Leftzhf** [coldenate/rollover-daily-todos#9]
**Is your feature request related to a problem? Please describe.**
Currently all todo's within the specified time will be rollover, but for some todo's, they may just be recorded temporarily and wait until a later time to be executed.So for these todo's, you can tag them with a specific tag like #Later in logseq so that they don't show up in the daily rollover.

**Describe the solution you'd like**
Supports providing no rollover for a specified Rem todo of one or more tags.

**Comment by coldenate** [comment]
I currently have a system for this with the `/Do not rollover` command. Run that command on a rem of your choice, and it will not show up in the rollover. 
Is this what you mean? The command tags the rem with a tag of the same functionality as #later (to my understanding).

**Comment by coldenate** [comment]
Have you gotten a change to test the command's functionality? @Leftzhf Do you have any feedback for the feature?
